name: gitlint
on: [push, pull_request]
jobs:
  checks:
    runs-on: "ubuntu-latest"
      #if: github.event_name == 'pull_request' || (github.event.before != '0000000000000000000000000000000000000000' && needs.pr-check.outputs.number)
    steps:
      - name: Debug print
        run: echo "github.event.before ${{github.event.before}}"
      - name: Debug print
        run: echo "checks ${{needs.pr-check.outputs.number}}"
        if: needs.pr-check.outputs.number
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
      - name: Install gitlint
        run: pip install gitlint
      - name: gitlint for PR
        run: gitlint --debug --commits ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
        if: github.event_name == 'pull_request'
      - name: gitlint for push event
        run: gitlint --debug --commits ${{ github.event.before }}..${{ github.event.after }}
        if: github.event_name == 'push'
